### ISSUE TITLE
Gå igenom och uppdatera vid behov automatiska regressionstester

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet_test#3]
_From @kamidev on September 23, 2015 8:44_

Samtliga incheckade automatiska tester ska gå igenom innan vi inför nya kodförändringar. 

Testsviterna bör struktureras så att det går att köra tester för skarpa lagrummet respektive beta-sajten separat.

_Copied from original issue: rinfo/lagrummet.se#446_

**Comment by kamidev** [comment]
Ersätt befintliga Casperjs-tester med Java-baserade tester som går att köra både via Browserstack och via kommandorad. Dokumentera hur man kör testsviter och enstaka tester.

**Comment by kamidev** [comment]
Tester som arbetar mot startsida för www.lagrummet.se ska vara tydligt åtskilda från de som går mot beta.lagrummet.se. Skapa helst separata testsviter.

**Comment by kamidev** [comment]
Detta ärende är för närvarande nerbrutet i dessa två: #1 och #2

**Comment by kamidev** [comment]
Detta ärende är nu flyttat till en separat applikation med eget repo: lagrummet_test.

**Comment by kamidev** [comment]
Ärende #1 är nu stängt. Endast webbläsarkompatibliteten återstår.

**Comment by Leome** [comment]
Beskrivning i README om hur man kör testerna mot browserstack (genom att skicka in system properties: lagrummet.browserstack.username samt lagrummet.browserstack.automatekey). Kan annars vara svårt att veta hur man ska dra igång dessa.

**Comment by Leome** [comment]
En logiksnurra för att automatiskt köra mot browserstack om browserstack-credentials skickas med. I annat fall köra lokalt med tex firefox-drivern.

**Comment by kamidev** [comment]
En testsvit enligt ovan finns incheckad och går att köra via  rinfo/lagrummet_test
